# Generated by Django 4.2.1 on 2023-06-10 17:34

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORIA',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='nombre de la categoria')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre')),
                ('is_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='INGREDIENTE',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='nombre')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre')),
                ('stock', models.IntegerField(verbose_name='stock')),
            ],
        ),
        migrations.CreateModel(
            name='ORDEN_PEDIDO',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('Barcode', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Barcode')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('imgurl', models.CharField(max_length=600, verbose_name='url_img')),
                ('descripcion', models.TextField(max_length=600, null=True, verbose_name='descripcion')),
                ('is_activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='STATUS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_status')),
                ('tipo_estado', models.CharField(max_length=50, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_DESPACHO',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Barcode')),
                ('Tnombre', models.CharField(max_length=50, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_PAGO',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Barcode')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO_ORDEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden_pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.AddField(
            model_name='orden_pedido',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
        migrations.AddField(
            model_name='orden_pedido',
            name='tipo_despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_despacho'),
        ),
        migrations.AddField(
            model_name='orden_pedido',
            name='tipo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_pago'),
        ),
        migrations.CreateModel(
            name='INGREDIENTE_PRODUCTO',
            fields=[
                ('union', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingrediente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='HISTORICO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='BOLETA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('cliente', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripcion')),
                ('total', models.IntegerField()),
                ('num_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden_pedido')),
            ],
        ),
    ]
