# Generated by Django 4.2.1 on 2023-06-29 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_pedido',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='num_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='core.orden_pedido'),
        ),
        migrations.AlterField(
            model_name='orden_pedido',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='tipo_estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipo_despacho',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_pago',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
