# Generated by Django 4.2.1 on 2023-05-12 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_boleta_id_alter_ordenpedido_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='IdIngrediente')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('nomProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
