# Generated by Django 4.2.1 on 2023-05-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingrediente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boleta',
        ),
    ]
