# Generated by Django 4.2.1 on 2023-05-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='nomProducto',
        ),
        migrations.RemoveField(
            model_name='listaordenpedido',
            name='id_orden',
        ),
        migrations.RemoveField(
            model_name='listaordenpedido',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='ordenpedido',
            name='nomCliente',
        ),
        migrations.RemoveField(
            model_name='ordenpedido',
            name='tipoPago',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='ListaOrdenPedido',
        ),
        migrations.DeleteModel(
            name='OrdenPedido',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='tipoPago',
        ),
    ]
