# Generated by Django 4.2.1 on 2023-05-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imgurl',
            field=models.CharField(max_length=600, verbose_name='url_img'),
        ),
    ]
